### ISSUE TITLE
Babylon file exported from 3ds Max 2018 doesn't load when using AssetsManager addMeshTask

### ISSUE THREAD

**Issue by gentlemanjohn** [BabylonJS/Exporters#77]
I just get purple space.  Exporting the same file to .obj, importing into Blender, and then exporting to .babylon "works" in the sense that it will load (there are problems with textures being off in association with going from Max -> OBJ).  

Also, the resulting babylon file using the Max exporter is huge: more than twice the size of Max file.  This  is not the case using the Blender exporter.

I'm using the latest 0.36.0 zip file.

These are the errors I see when I call `addMeshTask` (and presumably why I'm not seeing any of my meshes):

errorObject.message: 

> `"Unable to import meshes from assets/scenes/agency/babylon/agency.babylon: importMesh of agency.babylon from 3dsmax version: 2017, exporter version: 0.4.5
> 	Material Name: Floor
> 	Material Name: Walls
> 	Material Name: Ceiling
> 	Material Name: Baseboard
> 	Material Name: 23 - Default
> 	Multi-Material Name: Material #258
> 	Mesh Name: Room, isInstance: NO, # of submeshes: 4, n vertices: 276, parent: NONE
> 	Mesh Name: Camera001.Target, isInstance: NO, # of submeshes: 0, n vertices: 0, parent: NONE
> 	Material Name: Wood 01"`
(Despite the error I am using 3ds Max 2018)

errorObject.exception.message:

> `Cannot read property 'toString' of null`

**Comment by deltakosh** [comment]
We are stripping numbers to only 4 digits after zero in blender and not in 3dsmax hence the size difference
Can you share the exported Babylon.js file?

**Comment by gentlemanjohn** [comment]
@deltakosh 
[https://drive.google.com/file/d/1b20RZW3iJyAeBjgaWHNDnUNgpW5kFVAs/view?usp=sharing](https://drive.google.com/file/d/1b20RZW3iJyAeBjgaWHNDnUNgpW5kFVAs/view?usp=sharing)

**Comment by noalak** [comment]
Numbers are stripped to only 4 digits after zero in 3dsmax too.
Check if the "Try to optimize vertices" option applied to all meshes helps with file size.

**Comment by deltakosh** [comment]
@noalak do you repro the loading issue?
@gentlemanjohn can you share your loading code?

**Comment by gentlemanjohn** [comment]
@deltakosh 

I think this is all the relevant code.  It's in Angular 5:

```
private engine;
private scene;
private canvas;

...

initialize() {
    this.canvas = <HTMLCanvasElement>document.getElementById('renderCanvas');
    this.engine = new BABYLON.Engine(this.canvas, true);
    BABYLON.OBJFileLoader.OPTIMIZE_WITH_UV = true;
    this.createScene();
  }

...

createScene() {

this.scene = new BABYLON.Scene(this.engine);

...

let assetsManager = new BABYLON.AssetsManager(this.scene);
let meshTask = assetsManager.addMeshTask("agency task", "", "assets/scenes/agency/babylon/", "agency.babylon");
    meshTask.onSuccess = (task:BABYLON.MeshAssetTask) => {
      task.loadedMeshes[0].position = BABYLON.Vector3.Zero();
      for (let mesh of task.loadedMeshes) {
        console.log(mesh);
        mesh.checkCollisions = true;
      }
    }

    this.scene.registerBeforeRender(() => {
    });
    assetsManager.onFinish = (tasks) => {
      this.engine.runRenderLoop(() => {
        this.scene.render();
      });
    };
    assetsManager.load();
});
```

**Comment by deltakosh** [comment]
Ok this is now fixed :)
it will be available with the next nightly

**Comment by gentlemanjohn** [comment]
@deltakosh Was the fix included in 0.38.0? I'm still having the same issue.

**Comment by deltakosh** [comment]
It is a fix in the engine and not the exporter

**Comment by gentlemanjohn** [comment]
ah, gotcha, thanks
